spring:
  datasource:
    url: jdbc:mysql://localhost:3306/naturals?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: Momentalno11
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
